url: https://www.vnext.com.au
baseurl: /
header_background: img/header-bg-dark.jpg
contact_background: img/melbourne-map.jpg
form_url: https://formspree.io/has@vnext.com.au

# Site settings
title: vNEXT
email: hello@vnext.com.au
description: "PASSIONATE TECHNOLOGISTS WITH A HUMAN-LED APPROACH. We are an innovative bunch of enginners, who thrive on solving problems. We are facinated by the human-ingeniunity and excited about the potential of AI. We are on a mission to use AI and our years of expertise to augment human capabilities and create a competitve edge for our customers"

# Team names, titles and social links
people:
- name: Has Altaiar
  pic: img/team/has.jpg
  position: Principal Consultant
  social:
    - title: twitter
      url: https://twitter.com/hasaltaiar
    - title: linkedin
      url: https://www.linkedin.com/in/altaiar/
    - title: stack-overflow
      url: https://stackoverflow.com/users/1570662/has-altaiar

- name: Chris Melinn
  pic: img/team/chris.jpg
  position: Principal Consultant 
  social:
    - title: twitter
      url: http://twitter.com/chrismelinn
    - title: linkedin
      url: https://www.linkedin.com/in/chris-melinn-9a2978/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/vnext_au
  - title: facebook
    url: http://facebook.com/vnext_au
  - title: linkedin
    url: https://www.linkedin.com/company/vnextau/

# Postal address (add as many lines as necessary)
address:
  - line: Collins St
  - line: Melbourne, VIC 3000

# Build settings
markdown: kramdown
permalink: pretty

#---- Generate Career Postings
#
# See https://github.com/avillafiorita/jekyll-datapage_gen
#

page_gen:
  # - index_files: <<true or false> (optional) to generate named folder
  #   data: <<name of the data file to read (YAML, JSON, or CSV)>>
  #         Use the full path if your data is structured in a hierarchy. 
  #         For instance: hierarchy.people will loop over a variable people in the _data/hierarchy.yml file
  #   template: <<name of the template to use to generate the page>>
  #   name: <<the name of a field containing unique ID used to generate the filename>>
  #   name_expr : is an optional Ruby expression used to generate a filename. 
  #               Can reference fields of the data being read using the record hash
  #               (e.g., record['first_name'] + "_" + record['last_name']) 
  #               Optional: if set, this overrides name
  #   dir: <<directory in which files are to be generated>>
  #   extension : the extension of the generated file. Optional: defaults to ".html"
  #   filter : is a property of each data record that must return a true-ish value 
  #            for the record to be included in the list of files to be generated. 
  #            Optional: if not specified, all records from the dataset are included
  # filter_condition : is a string containing a Ruby expression which evaluates to a true-ish value. 
  #                    Can reference fields of the data being read using the record hash 
  #                    (e.g., record['author'] == 'George Orwell'). 
  #                    Optional: if not specified, all records from the dataset are included (see also filter).

  - index_files: false
    data: 'careers'
    template: 'careers'
    name: 'generated_page_name'
    dir: 'careers'
    filter: active
